# Generated by Django 2.2.6 on 2019-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('vanity_url', models.URLField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('org_id', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('live', 'live'), ('started', 'started'), ('ended', 'ended'), ('completed', 'completed'), ('cancelled', 'cancelled')], max_length=9)),
                ('currency', models.CharField(max_length=3)),
                ('online_event', models.BooleanField()),
                ('hide_start_date', models.BooleanField()),
                ('hide_end_date', models.BooleanField()),
            ],
        ),
    ]
