# Generated by Django 2.2.6 on 2019-10-08 23:18

from django.db import migrations
from datetime import datetime, timedelta
from dateutil.tz import gettz
import requests

def fetch_events(apps, schema_editor):
    end_date = (datetime.now()-timedelta(weeks=3)).strftime("%Y-%m-%dT%H:%M:%SZ")
    headers = {'Authorization':'Bearer <INSERT OAUTH HERE>','Accept-Encoding':'application/json'}
    params = {'start_date.keyword':'today','start_date.range_end':end_date}
    url = 'https://www.eventbriteapi.com/v3/events/search'
    r = requests.get(url,params=params,headers=headers,timeout=60)
    events = r.json()["events"]
    for e in events:
        event = Event(
            id = e['id'],
            name = e['name'],
            description = e['descroption']['text'],
            url = e['url'],
            vanity_url = e['vanity_url'],
            start = e['start']['utc'].strftime("%Y-%m-%dT%H:%M:%SZ").astimezone(gettz(e['timezone'])),
            end = e['end']['utc'].strftime("%Y-%m-%dT%H:%M:%SZ").astimezone(gettz(e['timezone'])),
            org_id = e['organization_id'],
            date_created = e['created'].strftime("%Y-%m-%dT%H:%M:%SZ"),
            date_modified = e['changed'].strftime("%Y-%m-%dT%H:%M:%SZ"),
            date_published = e['published'].strftime("%Y-%m-%dT%H:%M:%SZ"),
            status = e['status'],
            currency = e['currency'],
            online_event = e['online_event'],
            hide_start_date = e['hide_start_date'],
            hide_end_date = e['hide_end_date'],
        )
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fetch_events),
    ]
